export const SET_TAB_FILTER = 'SET_TAB_FILTER'
export const TAB_FILTERS = { 
  SHOW_TOP_MOVIES: 'SHOW_TOP_MOVIES', SHOW_TOP_TV: 'SHOW_TOP_TV' 
}
export const LOADING_TOP_CONTENT = 'LOADING_TOP_CONTENT'
export const RECEIVE_TOP_CONTENT = 'RECEIVE_TOP_CONTENT'
export const HANDLE_SEARCH_QUERY = 'HANDLE_SEARCH_QUERY'
export const LOADING_SEARCH_CONTENT = 'LOADING_SEARCH_CONTENT'
export const RECEIVE_SEARCH_CONTENT = 'RECEIVE_SEARCH_CONTENT'
export const SEARCH_WILL_START = 'SEARCH_WILL_START'
export const LOADING_INFO = 'LOADING_INFO'
export const RECEIVE_INFO = 'RECEIVE_INFO'